// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Kuzu",
    platforms: [.macOS(.v15)],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "Kuzu",
            targets: ["Kuzu"]
        ),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "Kuzu",
            path: ".",
            exclude: [
                // Main folder
                "benchmark",
                "build",
                "dataset",
                "examples",
                "extension",
                "logo",
                "scripts",
                "test",
                "tools",
                "CMakeLists.txt",
                "CODE_OF_CONDUCT.md",
                "CONTRIBUTING.md",
                "LICENSE",
                "Makefile",
                // Src
                "src/antlr4",
                "src/transaction/CMakeLists.txt",
                "src/CMakeLists.txt",
                "src/extension/CMakeLists.txt",
                "src/optimizer/CMakeLists.txt",
                "src/binder/rewriter/CMakeLists.txt",
                "src/binder/CMakeLists.txt",
                "src/binder/ddl/CMakeLists.txt",
                "src/binder/visitor/CMakeLists.txt",
                "src/binder/bind_expression/CMakeLists.txt",
                "src/binder/expression/CMakeLists.txt",
                "src/binder/query/CMakeLists.txt",
                "src/binder/bind/CMakeLists.txt",
                "src/binder/bind/ddl/CMakeLists.txt",
                "src/binder/bind/read/CMakeLists.txt",
                "src/binder/bind/copy/CMakeLists.txt",
                "src/planner/CMakeLists.txt",
                "src/planner/join_order/CMakeLists.txt",
                "src/planner/plan/CMakeLists.txt",
                "src/planner/operator/extend/CMakeLists.txt",
                "src/planner/operator/CMakeLists.txt",
                "src/planner/operator/persistent/CMakeLists.txt",
                "src/planner/operator/factorization/CMakeLists.txt",
                "src/planner/operator/ddl/CMakeLists.txt",
                "src/planner/operator/scan/CMakeLists.txt",
                "src/planner/operator/simple/CMakeLists.txt",
                "src/catalog/CMakeLists.txt",
                "src/catalog/catalog_entry/CMakeLists.txt",
                "src/processor/result/CMakeLists.txt",
                "src/processor/CMakeLists.txt",
                "src/processor/map/CMakeLists.txt",
                "src/processor/operator/CMakeLists.txt",
                "src/processor/operator/intersect/CMakeLists.txt",
                "src/processor/operator/table_scan/CMakeLists.txt",
                "src/processor/operator/persistent/reader/CMakeLists.txt",
                "src/processor/operator/persistent/reader/csv/CMakeLists.txt",
                "src/processor/operator/persistent/reader/parquet/CMakeLists.txt",
                "src/processor/operator/persistent/reader/npy/CMakeLists.txt",
                "src/processor/operator/persistent/CMakeLists.txt",
                "src/processor/operator/persistent/writer/parquet/CMakeLists.txt",
                "src/processor/operator/aggregate/CMakeLists.txt",
                "src/processor/operator/recursive_extend/CMakeLists.txt",
                "src/processor/operator/ddl/CMakeLists.txt",
                "src/processor/operator/scan/CMakeLists.txt",
                "src/processor/operator/hash_join/CMakeLists.txt",
                "src/processor/operator/simple/CMakeLists.txt",
                "src/processor/operator/macro/CMakeLists.txt",
                "src/processor/operator/order_by/CMakeLists.txt",
                "src/graph/CMakeLists.txt",
                "src/function/CMakeLists.txt",
                "src/function/array/CMakeLists.txt",
                "src/function/cast/CMakeLists.txt",
                "src/function/aggregate/CMakeLists.txt",
                "src/function/path/CMakeLists.txt",
                "src/function/date/CMakeLists.txt",
                "src/function/struct/CMakeLists.txt",
                "src/function/map/CMakeLists.txt",
                "src/function/gds/CMakeLists.txt",
                "src/function/table/CMakeLists.txt",
                "src/function/table/call/CMakeLists.txt",
                "src/function/list/CMakeLists.txt",
                "src/function/arithmetic/CMakeLists.txt",
                "src/function/union/CMakeLists.txt",
                "src/function/string/CMakeLists.txt",
                "src/function/pattern/CMakeLists.txt",
                "src/function/export/CMakeLists.txt",
                "src/function/sequence/CMakeLists.txt",
                "src/function/utility/CMakeLists.txt",
                "src/parser/antlr_parser/CMakeLists.txt",
                "src/parser/CMakeLists.txt",
                "src/parser/visitor/CMakeLists.txt",
                "src/parser/expression/CMakeLists.txt",
                "src/parser/transform/CMakeLists.txt",
                "src/storage/local_storage/CMakeLists.txt",
                "src/storage/predicate/CMakeLists.txt",
                "src/storage/CMakeLists.txt",
                "src/storage/wal/CMakeLists.txt",
                "src/storage/buffer_manager/CMakeLists.txt",
                "src/storage/storage_structure/CMakeLists.txt",
                "src/storage/compression/CMakeLists.txt",
                "src/storage/index/CMakeLists.txt",
                "src/storage/stats/CMakeLists.txt",
                "src/storage/store/CMakeLists.txt",
                "src/common/data_chunk/CMakeLists.txt",
                "src/common/serializer/CMakeLists.txt",
                "src/common/types/CMakeLists.txt",
                "src/common/types/value/CMakeLists.txt",
                "src/common/CMakeLists.txt",
                "src/common/arrow/CMakeLists.txt",
                "src/common/enums/CMakeLists.txt",
                "src/common/file_system/CMakeLists.txt",
                "src/common/copier_config/CMakeLists.txt",
                "src/common/task_system/CMakeLists.txt",
                "src/common/vector/CMakeLists.txt",
                "src/common/exception/CMakeLists.txt",
                "src/common/signal/CMakeLists.txt",
                "src/main/CMakeLists.txt",
                "src/c_api/CMakeLists.txt",
                "src/expression_evaluator/CMakeLists.txt",
                // Thrid patry
                "third_party/fast_float/CMakeLists.txt",
                "third_party/CMakeLists.txt",
                "third_party/pybind11/CMakeLists.txt",
                "third_party/brotli/CMakeLists.txt",
                "third_party/utf8proc/CMakeLists.txt",
                "third_party/mbedtls/CMakeLists.txt",
                "third_party/lz4/CMakeLists.txt",
                "third_party/alp/CMakeLists.txt",
                "third_party/miniz/CMakeLists.txt",
                "third_party/thrift/CMakeLists.txt",
                "third_party/fastpfor/CMakeLists.txt",
                "third_party/antlr4_cypher/CMakeLists.txt",
                "third_party/re2/CMakeLists.txt",
                "third_party/snappy/CMakeLists.txt",
                "third_party/zstd/CMakeLists.txt",
                "third_party/glob/CMakeLists.txt",
                "third_party/roaring_bitmap/CMakeLists.txt",
                "third_party/antlr4_runtime/CMakeLists.txt",
                "third_party/parquet/CMakeLists.txt",
                // find third_party -name "LICENSE*"
                "third_party/pcg/LICENSE",
                "third_party/pybind11/LICENSE",
                "third_party/brotli/LICENSE",
                "third_party/utf8proc/LICENSE.md",
                "third_party/mbedtls/LICENSE",
                "third_party/lz4/LICENSE",
                "third_party/alp/LICENSE",
                "third_party/miniz/LICENSE",
                "third_party/thrift/LICENSE",
                "third_party/fastpfor/LICENSE",
                "third_party/spdlog/LICENSE",
                "third_party/taywee_args/LICENSE",
                "third_party/re2/LICENSE",
                "third_party/snappy/LICENSE",
                "third_party/zstd/LICENSE",
                "third_party/antlr4_runtime/LICENSE",
                "third_party/parquet/LICENSE",
                // find third_party -name "*.in"
                "third_party/pybind11/tools/setup_main.py.in",
                "third_party/pybind11/tools/cmake_uninstall.cmake.in",
                "third_party/pybind11/tools/pybind11.pc.in",
                "third_party/pybind11/tools/setup_global.py.in",
                "third_party/pybind11/tools/pybind11Config.cmake.in",
                "third_party/brotli/scripts/libbrotlienc.pc.in",
                "third_party/brotli/scripts/libbrotlidec.pc.in",
                "third_party/brotli/scripts/libbrotlicommon.pc.in",
                "third_party/snappy/snappy-stubs-public.h.in",
                // find third_party -name "README*"
                "third_party/brotli/README",
                "third_party/brotli/README.md",
                "third_party/brotli/scripts/dictionary/README.md",
                "third_party/fastpfor/README",

                "third_party/thrift/protocol/TCompactProtocol.tcc",
                "third_party/spdlog/spdlog/fmt/bundled/fmt.license.rst",
                // brotli
                "third_party/brotli/CONTRIBUTING.md",
                "third_party/brotli/CHANGELOG.md",
                "third_party/brotli/SECURITY.md",
                "third_party/brotli/scripts",
                "third_party/brotli/docs",
                "third_party/brotli/fetch-spec",
                "third_party/brotli/c/tools",
                "third_party/brotli/c/fuzz",
                "third_party/brotli/c/common/dictionary.bin",
                "third_party/brotli/c/common/dictionary.bin.br",

                "third_party/antlr4_runtime/src/tree/xpath/XPathLexer.g4",
                "third_party/antlr4_runtime/src/tree/xpath/XPathLexer.tokens",
                // Don't need python binding
                "third_party/pybind11"
            ],
            sources: [
                "src",
                "third_party"
            ],
            publicHeadersPath: "src/include/c_api",
            cxxSettings: [
                // Defines
                .define("KUZU_CMAKE_VERSION", to: "\"0.7.1.1\""),
                .define("KUZU_EXTENSION_VERSION", to: "\"0.7.0\""),
                // Headers
                .headerSearchPath("src/include"),
                .headerSearchPath("third_party/alp/include"),
                .headerSearchPath("third_party/fast_float/include"),
                .headerSearchPath("third_party/roaring_bitmap"),
                .headerSearchPath("third_party/fastpfor"),
                .headerSearchPath("third_party/utf8proc/include"),
                .headerSearchPath("third_party/httplib"),
                .headerSearchPath("third_party/parquet"),
                .headerSearchPath("third_party/thrift"),
                .headerSearchPath("third_party/lz4"),
                .headerSearchPath("third_party/miniz"),
                .headerSearchPath("third_party/snappy"),
                .headerSearchPath("third_party/nlohmann_json"),
                .headerSearchPath("third_party/zstd/include"),
                .headerSearchPath("third_party/brotli/c/include"),
                .headerSearchPath("third_party/pyparse"),
                .headerSearchPath("third_party/antlr4_cypher/include"),
                .headerSearchPath("third_party/antlr4_runtime/src"),
                .headerSearchPath("third_party/pcg"),
                .headerSearchPath("third_party/re2/include"),
                .headerSearchPath("third_party/mbedtls/include"),
                .headerSearchPath("third_party/glob"),
            ]
        )
    ],
    cxxLanguageStandard: .cxx20
)
